api_key: 
api_base: http://127.0.0.1:1234/v1
model: jade_qwen3_4b_mlx
context_max_tokens: 8096
assistant_minimum_context_tokens: 1024
should_stream: false
stop_words:
- |2-

  <|im_start|>
- <|im_end|>
session_db_url: ""
session_name: bookclub_rummy
